# Generated by Django 2.2.16 on 2022-06-20 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopUnit',
            fields=[
                ('name', models.TextField(max_length=255)),
                ('date', models.DateTimeField()),
                ('type', models.TextField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=8)),
                ('price', models.IntegerField(null=True)),
                ('id', models.TextField(max_length=36, primary_key=True, serialize=False)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='goods.ShopUnit')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ShopUnitStatisticUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('date', models.DateTimeField()),
                ('type', models.TextField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=8)),
                ('price', models.IntegerField(null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_children', to='goods.ShopUnit')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='goods.ShopUnit')),
            ],
        ),
        migrations.AddConstraint(
            model_name='shopunitstatisticunit',
            constraint=models.UniqueConstraint(fields=('date', 'source'), name='unique_update'),
        ),
    ]
